2025-04-15 13:06:49,794 - INFO - Original file checksum: 1b76c230bce8c8c9a3333bb3485f3e682c5182c30bef1e21f6bf42a7b52e6ed7 - cli_test.py:44
2025-04-15 13:06:49,794 - INFO - File encrypted successfully: test.txt - cli_test.py:64
2025-04-15 13:09:18,114 - INFO - Backup created at: test.txt.bak - cli_test.py:94
2025-04-15 13:09:18,114 - INFO - File decrypted successfully: test.txt - cli_test.py:113
2025-04-15 13:34:54,781 - INFO - Logger initialized with rotating file handler. - log_manager.py:49
2025-04-15 13:34:54,781 - INFO - ====== STARTING LOGGING INTEGRATION TESTS ====== - test_logging.py:29
2025-04-15 13:34:54,781 - INFO - Test 1: Testing file operations logging - test_logging.py:33
2025-04-15 13:34:54,781 - INFO - Created test file at: C:\Users\oluwa\Documents\Griffith College Year 4 Sem 2\CSEH\Assignment\cseh_assignment\test_log_lvy0yamu.txt - test_logging.py:36
2025-04-15 13:34:54,797 - INFO - Operation: read_binary performed on file: test_log_lvy0yamu.txt - log_manager.py:59
2025-04-15 13:34:54,797 - INFO - Operation: checksum_calculated_sha256 performed on file: test_log_lvy0yamu.txt - log_manager.py:59
2025-04-15 13:34:54,797 - INFO - Operation: backup_created performed on file: test_log_lvy0yamu.txt.bak - log_manager.py:59
2025-04-15 13:34:54,797 - INFO - Operation: validate_access_success performed on file: test_log_lvy0yamu.txt - log_manager.py:59
2025-04-15 13:34:54,797 - INFO - Operation: write_binary performed on file: test_log_lvy0yamu.txt - log_manager.py:59
2025-04-15 13:34:54,797 - INFO - Test 1 completed: File operations with logging - test_logging.py:54
2025-04-15 13:34:54,797 - INFO - Test 2: Testing crypto operations logging - test_logging.py:57
2025-04-15 13:34:54,797 - INFO - New encryption key generated - crypto_engine.py:17
2025-04-15 13:34:54,797 - WARNING - Key validation failed: not valid base64 - crypto_engine.py:90
2025-04-15 13:34:54,797 - INFO - New encryption key generated - crypto_engine.py:17
2025-04-15 13:34:54,797 - INFO - Using newly generated encryption key - crypto_engine.py:27
2025-04-15 13:34:54,856 - INFO - New encryption key generated - crypto_engine.py:17
2025-04-15 13:34:54,857 - ERROR - Error Type: DecryptionError | Message: Decryption failed - Invalid token - log_manager.py:68
2025-04-15 13:34:54,857 - ERROR - Error Type: DecryptionError | Message: Unexpected error during decryption - log_manager.py:68
2025-04-15 13:34:54,857 - INFO - Expected error caught: Decryption with wrong key - test_logging.py:83
2025-04-15 13:34:54,857 - INFO - Test 2 completed: Crypto operations with logging - test_logging.py:85
2025-04-15 13:34:54,857 - INFO - Test 3: Testing error logging - test_logging.py:88
2025-04-15 13:34:54,857 - ERROR - Error Type: FileNotFoundError | Message: File not found: non_existent_file.txt - log_manager.py:68
2025-04-15 13:34:54,857 - INFO - Expected error caught: File not found - test_logging.py:94
2025-04-15 13:34:54,862 - ERROR - Error Type: PermissionError | Message: Simulated permission denied error - log_manager.py:68
2025-04-15 13:34:54,863 - ERROR - Error Type: DecryptionError | Message: Decryption failed - Invalid token - log_manager.py:68
2025-04-15 13:34:54,863 - ERROR - Error Type: DecryptionError | Message: Unexpected error during decryption - log_manager.py:68
2025-04-15 13:34:54,864 - INFO - Expected error caught: Corrupted data - test_logging.py:105
2025-04-15 13:34:54,864 - INFO - Test 3 completed: Error logging - test_logging.py:107
2025-04-15 13:34:54,865 - INFO - ====== COMPLETED LOGGING INTEGRATION TESTS ====== - test_logging.py:123
2025-04-15 14:17:18,091 - INFO - Logger initialized with rotating file handler. - log_manager.py:49
2025-04-15 14:17:18,091 - INFO - Application starting... - main.py:75
2025-04-15 14:17:18,668 - INFO - Application initialized successfully. Version: Unknown - main.py:126
2025-04-15 14:18:00,338 - INFO - Operation: validate_access_success performed on file: test.txt - log_manager.py:59
2025-04-15 14:18:22,182 - INFO - Operation: read_binary performed on file: test.txt - log_manager.py:59
2025-04-15 14:18:22,185 - INFO - New encryption key generated - crypto_engine.py:17
2025-04-15 14:18:22,185 - INFO - Using newly generated encryption key - crypto_engine.py:27
2025-04-15 14:18:22,235 - INFO - Operation: write_binary performed on file: test.txt - log_manager.py:59
2025-04-15 14:18:22,235 - INFO - Operation: encrypt performed on file: test.txt - log_manager.py:59
2025-04-15 14:18:59,445 - INFO - Operation: read_binary performed on file: test.txt - log_manager.py:59
2025-04-15 14:18:59,445 - INFO - New encryption key generated - crypto_engine.py:17
2025-04-15 14:18:59,460 - INFO - Using newly generated encryption key - crypto_engine.py:27
2025-04-15 14:18:59,464 - INFO - Operation: write_binary performed on file: test.txt - log_manager.py:59
2025-04-15 14:18:59,464 - INFO - Operation: encrypt performed on file: test.txt - log_manager.py:59
2025-04-15 14:19:10,541 - INFO - Application shutting down... - main.py:97
2025-04-15 14:20:14,501 - INFO - Logger initialized with rotating file handler. - log_manager.py:49
2025-04-15 14:20:14,501 - INFO - Application starting... - main.py:75
2025-04-15 14:20:14,577 - INFO - Application initialized successfully. Version: Unknown - main.py:126
2025-04-15 14:20:25,658 - INFO - Operation: validate_access_success performed on file: test.txt - log_manager.py:59
2025-04-15 14:20:27,424 - INFO - Operation: read_binary performed on file: test.txt - log_manager.py:59
2025-04-15 14:20:27,424 - INFO - New encryption key generated - crypto_engine.py:17
2025-04-15 14:20:27,424 - INFO - Using newly generated encryption key - crypto_engine.py:27
2025-04-15 14:20:27,454 - INFO - Operation: write_binary performed on file: test.txt - log_manager.py:59
2025-04-15 14:20:27,454 - INFO - Operation: encrypt performed on file: test.txt - log_manager.py:59
2025-04-15 14:20:42,343 - INFO - Application shutting down... - main.py:97
2025-04-15 14:23:45,541 - INFO - Logger initialized with rotating file handler. - log_manager.py:49
2025-04-15 14:23:45,541 - INFO - Application starting... - main.py:75
2025-04-15 14:23:45,613 - INFO - Application initialized successfully. Version: Unknown - main.py:126
2025-04-15 14:24:10,772 - INFO - Operation: validate_access_success performed on file: test.txt - log_manager.py:59
2025-04-15 14:24:12,664 - INFO - Operation: read_binary performed on file: test.txt - log_manager.py:59
2025-04-15 14:24:12,666 - INFO - New encryption key generated - crypto_engine.py:17
2025-04-15 14:24:12,666 - INFO - Using newly generated encryption key - crypto_engine.py:27
2025-04-15 14:24:12,710 - INFO - Operation: write_binary performed on file: test.txt - log_manager.py:59
2025-04-15 14:24:12,710 - INFO - Operation: encrypt performed on file: test.txt - log_manager.py:59
2025-04-15 14:24:17,287 - INFO - Application shutting down... - main.py:97
2025-04-15 14:26:41,586 - INFO - Logger initialized with rotating file handler. - log_manager.py:49
2025-04-15 14:26:41,587 - INFO - Application starting... - main.py:75
2025-04-15 14:26:41,652 - INFO - Application initialized successfully. Version: 1.0.0 - main.py:126
2025-04-15 14:26:55,099 - INFO - Application shutting down... - main.py:97
2025-04-15 14:30:10,570 - INFO - Logger initialized with rotating file handler. - log_manager.py:49
2025-04-15 14:30:10,570 - INFO - Application starting... - main.py:75
2025-04-15 14:30:10,653 - INFO - Application initialized successfully. Version: 1.0.0 - main.py:126
2025-04-15 14:30:17,681 - INFO - Operation: validate_access_success performed on file: test.txt - log_manager.py:59
2025-04-15 14:30:19,014 - INFO - Operation: read_binary performed on file: test.txt - log_manager.py:59
2025-04-15 14:30:19,014 - INFO - New encryption key generated - crypto_engine.py:17
2025-04-15 14:30:19,019 - INFO - Using newly generated encryption key - crypto_engine.py:27
2025-04-15 14:30:19,029 - INFO - Operation: write_binary performed on file: test.txt - log_manager.py:59
2025-04-15 14:30:19,029 - INFO - Operation: encrypt performed on file: test.txt - log_manager.py:59
2025-04-15 14:30:56,122 - INFO - Operation: read_binary performed on file: test.txt - log_manager.py:59
2025-04-15 14:30:56,138 - INFO - Operation: backup_created performed on file: test.txt.bak - log_manager.py:59
2025-04-15 14:30:56,139 - INFO - Operation: backup performed on file: test.txt.bak - log_manager.py:59
2025-04-15 14:30:56,141 - INFO - Operation: write_binary performed on file: test.txt - log_manager.py:59
2025-04-15 14:30:56,142 - INFO - Operation: decrypt performed on file: test.txt - log_manager.py:59
2025-04-15 14:33:29,559 - INFO - Operation: validate_access_success performed on file: This is a test file.txt - log_manager.py:59
2025-04-15 14:33:37,451 - INFO - Operation: read_binary performed on file: This is a test file.txt - log_manager.py:59
2025-04-15 14:33:37,451 - INFO - New encryption key generated - crypto_engine.py:17
2025-04-15 14:33:37,453 - INFO - Using newly generated encryption key - crypto_engine.py:27
2025-04-15 14:33:37,457 - INFO - Operation: write_binary performed on file: This is a test file.txt - log_manager.py:59
2025-04-15 14:33:37,457 - INFO - Operation: encrypt performed on file: This is a test file.txt - log_manager.py:59
2025-04-15 14:33:52,960 - INFO - Operation: read_binary performed on file: This is a test file.txt - log_manager.py:59
2025-04-15 14:33:52,962 - ERROR - Error Type: DecryptionError | Message: Decryption failed - Invalid token - log_manager.py:68
2025-04-15 14:33:52,962 - ERROR - Error Type: DecryptionError | Message: Unexpected error during decryption - log_manager.py:68
2025-04-15 14:33:52,962 - ERROR - Error Type: decryption_error | Message: Decryption failed. Possibly due to an incorrect key or corrupted data. - log_manager.py:68
2025-04-15 14:34:01,987 - INFO - Operation: read_binary performed on file: This is a test file.txt - log_manager.py:59
2025-04-15 14:34:02,003 - ERROR - Error Type: DecryptionError | Message: Decryption failed - Invalid token - log_manager.py:68
2025-04-15 14:34:02,003 - ERROR - Error Type: DecryptionError | Message: Unexpected error during decryption - log_manager.py:68
2025-04-15 14:34:02,003 - ERROR - Error Type: decryption_error | Message: Decryption failed. Possibly due to an incorrect key or corrupted data. - log_manager.py:68
2025-04-15 14:34:19,709 - INFO - Operation: read_binary performed on file: This is a test file.txt - log_manager.py:59
2025-04-15 14:34:19,709 - INFO - New encryption key generated - crypto_engine.py:17
2025-04-15 14:34:19,709 - INFO - Using newly generated encryption key - crypto_engine.py:27
2025-04-15 14:34:19,740 - INFO - Operation: write_binary performed on file: This is a test file.txt - log_manager.py:59
2025-04-15 14:34:19,756 - INFO - Operation: encrypt performed on file: This is a test file.txt - log_manager.py:59
2025-04-15 14:34:30,325 - INFO - Operation: read_binary performed on file: This is a test file.txt - log_manager.py:59
2025-04-15 14:34:30,341 - ERROR - Error Type: DecryptionError | Message: Decryption failed - Invalid token - log_manager.py:68
2025-04-15 14:34:30,341 - ERROR - Error Type: DecryptionError | Message: Unexpected error during decryption - log_manager.py:68
2025-04-15 14:34:30,341 - ERROR - Error Type: decryption_error | Message: Decryption failed. Possibly due to an incorrect key or corrupted data. - log_manager.py:68
2025-04-15 14:34:33,953 - INFO - Operation: read_binary performed on file: This is a test file.txt - log_manager.py:59
2025-04-15 14:34:33,953 - INFO - New encryption key generated - crypto_engine.py:17
2025-04-15 14:34:33,964 - INFO - Using newly generated encryption key - crypto_engine.py:27
2025-04-15 14:34:33,996 - INFO - Operation: write_binary performed on file: This is a test file.txt - log_manager.py:59
2025-04-15 14:34:33,996 - INFO - Operation: encrypt performed on file: This is a test file.txt - log_manager.py:59
2025-04-15 14:34:44,132 - INFO - Operation: read_binary performed on file: This is a test file.txt - log_manager.py:59
2025-04-15 14:34:44,132 - INFO - Operation: backup_created performed on file: This is a test file.txt.bak - log_manager.py:59
2025-04-15 14:34:44,132 - INFO - Operation: backup performed on file: This is a test file.txt.bak - log_manager.py:59
2025-04-15 14:34:44,132 - INFO - Operation: write_binary performed on file: This is a test file.txt - log_manager.py:59
2025-04-15 14:34:44,132 - INFO - Operation: decrypt performed on file: This is a test file.txt - log_manager.py:59
2025-04-15 14:44:42,389 - ERROR - Error Type: CriticalError | Message: Unhandled exception: Traceback (most recent call last):
  File "c:\Users\oluwa\Documents\Griffith College Year 4 Sem 2\CSEH\Assignment\cseh_assignment\main.py", line 144, in <module>
    exit_code = main()
                ^^^^^^
  File "c:\Users\oluwa\Documents\Griffith College Year 4 Sem 2\CSEH\Assignment\cseh_assignment\main.py", line 129, in main
    root.mainloop()
  File "C:\Python312\Lib\tkinter\__init__.py", line 1485, in mainloop
    self.tk.mainloop(n)
KeyboardInterrupt
 - log_manager.py:68
2025-04-15 14:44:55,855 - INFO - Logger initialized with rotating file handler. - log_manager.py:49
2025-04-15 14:44:55,855 - INFO - Application starting... - main.py:75
2025-04-15 14:44:55,932 - INFO - Application initialized successfully. Version: 1.0.0 - main.py:126
2025-04-15 14:45:14,624 - INFO - Operation: validate_access_success performed on file: test.txt - log_manager.py:59
2025-04-15 14:45:18,997 - INFO - Operation: read_binary performed on file: test.txt - log_manager.py:59
2025-04-15 14:45:18,997 - INFO - New encryption key generated - crypto_engine.py:17
2025-04-15 14:45:18,997 - INFO - Using newly generated encryption key - crypto_engine.py:27
2025-04-15 14:45:19,015 - INFO - Operation: write_binary performed on file: test.txt - log_manager.py:59
2025-04-15 14:45:19,015 - INFO - Operation: encrypt performed on file: test.txt - log_manager.py:59
2025-04-15 14:45:39,630 - INFO - Operation: read_binary performed on file: test.txt - log_manager.py:59
2025-04-15 14:45:39,630 - INFO - Operation: backup_created performed on file: test.txt.bak - log_manager.py:59
2025-04-15 14:45:39,630 - INFO - Operation: backup performed on file: test.txt.bak - log_manager.py:59
2025-04-15 14:45:39,645 - INFO - Operation: write_binary performed on file: test.txt - log_manager.py:59
2025-04-15 14:45:39,645 - INFO - Operation: decrypt performed on file: test.txt - log_manager.py:59
2025-04-15 14:46:38,016 - INFO - Operation: read_binary performed on file: test.txt - log_manager.py:59
2025-04-15 14:46:38,016 - INFO - Operation: backup_created performed on file: test.txt.bak - log_manager.py:59
2025-04-15 14:46:38,016 - INFO - Operation: backup performed on file: test.txt.bak - log_manager.py:59
2025-04-15 14:46:38,030 - ERROR - Error Type: DecryptionError | Message: Decryption failed - Invalid token - log_manager.py:68
2025-04-15 14:46:38,030 - ERROR - Error Type: DecryptionError | Message: Unexpected error during decryption: ValueError - log_manager.py:68
2025-04-15 14:46:56,419 - INFO - Application shutting down... - main.py:97
2025-04-15 15:02:32,451 - INFO - Logger initialized with rotating file handler. - log_manager.py:49
2025-04-15 15:02:32,451 - INFO - Application starting... - main.py:75
2025-04-15 15:02:33,674 - INFO - Application initialized successfully. Version: 1.0.0 - main.py:126
2025-04-15 15:02:49,612 - INFO - Operation: validate_access_success performed on file: test.txt - log_manager.py:59
2025-04-15 15:03:30,216 - INFO - Application shutting down... - main.py:97
2025-04-15 15:10:43,724 - INFO - Logger initialized with rotating file handler. - log_manager.py:49
2025-04-15 15:10:43,724 - INFO - Application starting... - main.py:75
2025-04-15 15:10:43,808 - INFO - Application initialized successfully. Version: 1.0.0 - main.py:126
2025-04-15 15:11:02,420 - INFO - Operation: validate_access_success performed on file: test.txt - log_manager.py:59
2025-04-15 15:11:08,785 - INFO - Operation: read_binary performed on file: test.txt - log_manager.py:59
2025-04-15 15:11:08,785 - INFO - New encryption key generated - crypto_engine.py:17
2025-04-15 15:11:08,785 - INFO - Using newly generated encryption key - crypto_engine.py:27
2025-04-15 15:11:08,820 - INFO - Operation: write_binary performed on file: test.txt - log_manager.py:59
2025-04-15 15:11:08,820 - INFO - Operation: encrypt performed on file: test.txt - log_manager.py:59
2025-04-15 15:11:25,916 - INFO - Operation: read_binary performed on file: test.txt - log_manager.py:59
2025-04-15 15:11:25,916 - INFO - Operation: backup_created performed on file: test.txt.bak - log_manager.py:59
2025-04-15 15:11:25,916 - INFO - Operation: backup performed on file: test.txt.bak - log_manager.py:59
2025-04-15 15:11:25,931 - INFO - Operation: write_binary performed on file: test.txt - log_manager.py:59
2025-04-15 15:11:25,931 - INFO - Operation: decrypt performed on file: test.txt - log_manager.py:59
2025-04-15 15:23:27,712 - ERROR - Error Type: CriticalError | Message: Unhandled exception: Traceback (most recent call last):
  File "c:\Users\oluwa\Documents\Griffith College Year 4 Sem 2\CSEH\Assignment\cseh_assignment\main.py", line 144, in <module>
    exit_code = main()
                ^^^^^^
  File "c:\Users\oluwa\Documents\Griffith College Year 4 Sem 2\CSEH\Assignment\cseh_assignment\main.py", line 129, in main
    root.mainloop()
  File "C:\Python312\Lib\tkinter\__init__.py", line 1485, in mainloop
    self.tk.mainloop(n)
KeyboardInterrupt
 - log_manager.py:68
2025-04-15 15:23:41,392 - INFO - Logger initialized with rotating file handler. - log_manager.py:49
2025-04-15 15:23:41,392 - INFO - Application starting... - main.py:75
2025-04-15 15:23:41,478 - INFO - Application initialized successfully. Version: 1.0.0 - main.py:126
2025-04-15 15:24:00,373 - INFO - Operation: validate_access_success performed on file: test.txt - log_manager.py:59
2025-04-15 15:24:06,911 - INFO - Operation: read_binary performed on file: test.txt - log_manager.py:59
2025-04-15 15:24:06,911 - INFO - New encryption key generated - crypto_engine.py:17
2025-04-15 15:24:06,911 - INFO - Using newly generated encryption key - crypto_engine.py:27
2025-04-15 15:24:06,930 - INFO - Operation: write_binary performed on file: test.txt - log_manager.py:59
2025-04-15 15:24:06,930 - INFO - Operation: encrypt performed on file: test.txt - log_manager.py:59
2025-04-15 15:24:24,264 - INFO - Application shutting down... - main.py:97
2025-04-15 17:33:12,301 - INFO - Logger initialized with rotating file handler. - log_manager.py:49
2025-04-15 17:33:12,301 - INFO - Application starting... - main.py:75
2025-04-15 17:33:12,374 - ERROR - Error Type: StartupError | Message: Failed to initialize application: module 'config' has no attribute 'BACKGROUND_COLOR' - log_manager.py:68
2025-04-15 17:36:52,357 - INFO - Logger initialized with rotating file handler. - log_manager.py:49
2025-04-15 17:36:52,357 - INFO - Application starting... - main.py:75
2025-04-15 17:36:52,452 - INFO - Application initialized successfully. Version: 1.0.0 - main.py:126
2025-04-15 17:37:07,544 - INFO - Operation: validate_access_success performed on file: test.txt - log_manager.py:59
2025-04-15 17:37:13,031 - INFO - Operation: read_binary performed on file: test.txt - log_manager.py:59
2025-04-15 17:37:13,031 - INFO - New encryption key generated - crypto_engine.py:17
2025-04-15 17:37:13,031 - INFO - Using newly generated encryption key - crypto_engine.py:27
2025-04-15 17:37:13,053 - INFO - Operation: write_binary performed on file: test.txt - log_manager.py:59
2025-04-15 17:37:13,053 - INFO - Operation: encrypt performed on file: test.txt - log_manager.py:59
2025-04-15 17:37:24,361 - INFO - Application shutting down... - main.py:97
2025-04-15 17:37:39,357 - INFO - Logger initialized with rotating file handler. - log_manager.py:49
2025-04-15 17:37:39,357 - INFO - Application starting... - main.py:75
2025-04-15 17:37:39,428 - INFO - Application initialized successfully. Version: 1.0.0 - main.py:126
2025-04-15 17:37:43,761 - INFO - Operation: validate_access_success performed on file: test.txt - log_manager.py:59
2025-04-15 17:37:46,905 - INFO - Operation: read_binary performed on file: test.txt - log_manager.py:59
2025-04-15 17:37:46,905 - INFO - New encryption key generated - crypto_engine.py:17
2025-04-15 17:37:46,920 - INFO - Using newly generated encryption key - crypto_engine.py:27
2025-04-15 17:37:46,931 - INFO - Operation: write_binary performed on file: test.txt - log_manager.py:59
2025-04-15 17:37:46,931 - INFO - Operation: encrypt performed on file: test.txt - log_manager.py:59
2025-04-15 17:37:59,443 - INFO - Operation: read_binary performed on file: test.txt - log_manager.py:59
2025-04-15 17:37:59,443 - INFO - Operation: backup_created performed on file: test.txt.bak - log_manager.py:59
2025-04-15 17:37:59,443 - INFO - Operation: backup performed on file: test.txt.bak - log_manager.py:59
2025-04-15 17:37:59,458 - INFO - Operation: write_binary performed on file: test.txt - log_manager.py:59
2025-04-15 17:37:59,459 - INFO - Operation: decrypt performed on file: test.txt - log_manager.py:59
2025-04-15 17:43:07,614 - ERROR - Error Type: CriticalError | Message: Unhandled exception: Traceback (most recent call last):
  File "c:\Users\oluwa\Documents\Griffith College Year 4 Sem 2\CSEH\Assignment\cseh_assignment\main.py", line 144, in <module>
    # Log startup success
            ^^^^^^
  File "c:\Users\oluwa\Documents\Griffith College Year 4 Sem 2\CSEH\Assignment\cseh_assignment\main.py", line 129, in main
    sys.excepthook = handle_exception
        ^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\tkinter\__init__.py", line 1485, in mainloop
    self.tk.mainloop(n)
KeyboardInterrupt
 - log_manager.py:68
2025-04-15 17:43:15,520 - INFO - Logger initialized with rotating file handler. - log_manager.py:49
2025-04-15 17:43:15,536 - INFO - Application starting... - main.py:75
2025-04-15 17:43:16,452 - INFO - Application initialized successfully. Version: 1.0.0 - main.py:145
2025-04-15 17:43:53,537 - INFO - Operation: validate_access_success performed on file: test.txt - log_manager.py:59
2025-04-15 17:44:00,601 - INFO - Operation: read_binary performed on file: test.txt - log_manager.py:59
2025-04-15 17:44:00,601 - INFO - New encryption key generated - crypto_engine.py:17
2025-04-15 17:44:00,601 - INFO - Using newly generated encryption key - crypto_engine.py:27
2025-04-15 17:44:00,611 - INFO - Operation: write_binary performed on file: test.txt - log_manager.py:59
2025-04-15 17:44:00,612 - INFO - Operation: encrypt performed on file: test.txt - log_manager.py:59
2025-04-15 17:44:49,285 - INFO - Application shutting down... - main.py:116
2025-04-15 17:48:36,998 - INFO - Logger initialized with rotating file handler. - log_manager.py:49
2025-04-15 17:48:36,998 - INFO - Application starting... - main.py:75
2025-04-15 17:48:37,101 - INFO - Application initialized successfully. Version: 1.0.0 - main.py:126
2025-04-15 17:48:50,225 - INFO - Application shutting down... - main.py:97
2025-04-15 17:51:17,030 - INFO - Logger initialized with rotating file handler. - log_manager.py:49
2025-04-15 17:51:17,030 - INFO - Application starting... - main.py:75
2025-04-15 17:51:17,668 - INFO - Application initialized successfully. Version: 1.0.0 - main.py:145
2025-04-15 17:51:25,790 - INFO - Operation: validate_access_success performed on file: test.txt - log_manager.py:59
2025-04-15 17:51:35,000 - INFO - Operation: read_binary performed on file: test.txt - log_manager.py:59
2025-04-15 17:51:35,000 - INFO - New encryption key generated - crypto_engine.py:17
2025-04-15 17:51:35,015 - INFO - Using newly generated encryption key - crypto_engine.py:27
2025-04-15 17:51:35,027 - INFO - Operation: write_binary performed on file: test.txt - log_manager.py:59
2025-04-15 17:51:35,027 - INFO - Operation: encrypt performed on file: test.txt - log_manager.py:59
2025-04-15 17:54:41,106 - INFO - Application shutting down... - main.py:116
2025-04-15 17:55:29,929 - INFO - Logger initialized with rotating file handler. - log_manager.py:49
2025-04-15 17:55:29,929 - INFO - Application starting... - main.py:75
2025-04-15 17:55:30,834 - INFO - Application initialized successfully. Version: 1.0.0 - main.py:145
2025-04-15 17:55:42,529 - INFO - Operation: validate_access_success performed on file: test.txt - log_manager.py:59
2025-04-15 17:55:45,514 - INFO - Operation: read_binary performed on file: test.txt - log_manager.py:59
2025-04-15 17:55:45,514 - INFO - New encryption key generated - crypto_engine.py:17
2025-04-15 17:55:45,514 - INFO - Using newly generated encryption key - crypto_engine.py:27
2025-04-15 17:55:45,538 - INFO - Operation: write_binary performed on file: test.txt - log_manager.py:59
2025-04-15 17:55:45,538 - INFO - Operation: encrypt performed on file: test.txt - log_manager.py:59
2025-04-15 17:59:27,418 - ERROR - Error Type: CriticalError | Message: Unhandled exception: Traceback (most recent call last):
  File "c:\Users\oluwa\Documents\Griffith College Year 4 Sem 2\CSEH\Assignment\cseh_assignment\main.py", line 163, in <module>
  File "c:\Users\oluwa\Documents\Griffith College Year 4 Sem 2\CSEH\Assignment\cseh_assignment\main.py", line 148, in main
  File "C:\Python312\Lib\tkinter\__init__.py", line 1485, in mainloop
    self.tk.mainloop(n)
KeyboardInterrupt
 - log_manager.py:68
2025-04-15 17:59:34,328 - INFO - Logger initialized with rotating file handler. - log_manager.py:49
2025-04-15 17:59:34,328 - INFO - Application starting... - main.py:75
2025-04-15 17:59:34,410 - INFO - Application initialized successfully. Version: 1.0.0 - main.py:126
2025-04-15 17:59:53,376 - INFO - Operation: validate_access_success performed on file: test.txt - log_manager.py:59
2025-04-15 18:00:05,560 - INFO - Application shutting down... - main.py:97
2025-04-15 18:01:58,677 - INFO - Logger initialized with rotating file handler. - log_manager.py:49
2025-04-15 18:01:58,677 - INFO - Application starting... - main.py:75
2025-04-15 18:01:59,595 - INFO - Application initialized successfully. Version: 1.0.0 - main.py:145
2025-04-15 18:02:05,398 - INFO - Operation: validate_access_success performed on file: test.txt - log_manager.py:59
2025-04-15 18:02:12,558 - INFO - Operation: read_binary performed on file: test.txt - log_manager.py:59
2025-04-15 18:02:12,558 - INFO - New encryption key generated - crypto_engine.py:17
2025-04-15 18:02:12,558 - INFO - Using newly generated encryption key - crypto_engine.py:27
2025-04-15 18:02:12,577 - INFO - Operation: write_binary performed on file: test.txt - log_manager.py:59
2025-04-15 18:02:12,577 - INFO - Operation: encrypt performed on file: test.txt - log_manager.py:59
2025-04-15 18:02:27,083 - INFO - Application shutting down... - main.py:116
2025-04-15 18:03:14,696 - INFO - Logger initialized with rotating file handler. - log_manager.py:49
2025-04-15 18:03:14,696 - INFO - Application starting... - main.py:75
2025-04-15 18:03:15,519 - INFO - Application initialized successfully. Version: 1.0.0 - main.py:145
2025-04-15 18:03:19,441 - INFO - Operation: validate_access_success performed on file: test.txt - log_manager.py:59
2025-04-15 18:03:34,464 - INFO - Operation: read_binary performed on file: test.txt - log_manager.py:59
2025-04-15 18:03:34,464 - INFO - New encryption key generated - crypto_engine.py:17
2025-04-15 18:03:34,464 - INFO - Using newly generated encryption key - crypto_engine.py:27
2025-04-15 18:03:34,482 - INFO - Operation: write_binary performed on file: test.txt - log_manager.py:59
2025-04-15 18:03:34,482 - INFO - Operation: encrypt performed on file: test.txt - log_manager.py:59
2025-04-15 18:10:46,320 - ERROR - Error Type: CriticalError | Message: Unhandled exception: Traceback (most recent call last):
  File "c:\Users\oluwa\Documents\Griffith College Year 4 Sem 2\CSEH\Assignment\cseh_assignment\main.py", line 163, in <module>
    exit_code = main()
                ^^^^^^
  File "c:\Users\oluwa\Documents\Griffith College Year 4 Sem 2\CSEH\Assignment\cseh_assignment\main.py", line 148, in main
    root.mainloop()
  File "C:\Python312\Lib\tkinter\__init__.py", line 1485, in mainloop
    self.tk.mainloop(n)
KeyboardInterrupt
 - log_manager.py:68
2025-04-15 18:10:52,173 - INFO - Logger initialized with rotating file handler. - log_manager.py:49
2025-04-15 18:10:52,189 - INFO - Application starting... - main.py:75
2025-04-15 18:10:52,858 - INFO - Application initialized successfully. Version: 1.0.0 - main.py:145
2025-04-15 18:10:57,600 - INFO - Operation: validate_access_success performed on file: test.txt - log_manager.py:59
2025-04-15 18:11:01,286 - INFO - Operation: read_binary performed on file: test.txt - log_manager.py:59
2025-04-15 18:11:01,286 - INFO - New encryption key generated - crypto_engine.py:17
2025-04-15 18:11:01,286 - INFO - Using newly generated encryption key - crypto_engine.py:27
2025-04-15 18:11:01,306 - INFO - Operation: write_binary performed on file: test.txt - log_manager.py:59
2025-04-15 18:11:01,306 - INFO - Operation: encrypt performed on file: test.txt - log_manager.py:59
2025-04-15 18:11:26,239 - INFO - Application shutting down... - main.py:116
2025-04-15 18:18:48,084 - INFO - Logger initialized with rotating file handler. - log_manager.py:49
2025-04-15 18:18:48,084 - INFO - Application starting... - main.py:75
2025-04-15 18:18:48,735 - INFO - Application initialized successfully. Version: 1.0.0 - main.py:145
2025-04-15 18:18:54,660 - INFO - Operation: validate_access_success performed on file: test.txt - log_manager.py:59
2025-04-15 18:18:55,880 - INFO - Operation: read_binary performed on file: test.txt - log_manager.py:59
2025-04-15 18:18:55,880 - INFO - New encryption key generated - crypto_engine.py:17
2025-04-15 18:18:55,880 - INFO - Using newly generated encryption key - crypto_engine.py:27
2025-04-15 18:18:55,890 - INFO - Operation: write_binary performed on file: test.txt - log_manager.py:59
2025-04-15 18:18:55,890 - INFO - Operation: encrypt performed on file: test.txt - log_manager.py:59
2025-04-15 18:19:12,487 - INFO - Application shutting down... - main.py:116
2025-04-15 18:22:06,367 - INFO - Logger initialized with rotating file handler. - log_manager.py:49
2025-04-15 18:22:06,368 - INFO - Application starting... - main.py:75
2025-04-15 18:22:06,444 - ERROR - Error Type: StartupError | Message: Failed to initialize application: module 'config' has no attribute 'BUTTON_COLOR' - log_manager.py:68
2025-04-15 18:24:30,111 - INFO - Logger initialized with rotating file handler. - log_manager.py:49
2025-04-15 18:24:30,111 - INFO - Application starting... - main.py:75
2025-04-15 18:24:30,181 - INFO - Application initialized successfully. Version: 1.0.0 - main.py:126
2025-04-15 18:24:43,125 - INFO - Operation: validate_access_success performed on file: test.txt - log_manager.py:59
2025-04-15 18:24:45,434 - INFO - Operation: read_binary performed on file: test.txt - log_manager.py:59
2025-04-15 18:24:45,434 - INFO - New encryption key generated - crypto_engine.py:17
2025-04-15 18:24:45,434 - INFO - Using newly generated encryption key - crypto_engine.py:27
2025-04-15 18:24:45,451 - INFO - Operation: write_binary performed on file: test.txt - log_manager.py:59
2025-04-15 18:24:45,451 - INFO - Operation: encrypt performed on file: test.txt - log_manager.py:59
2025-04-15 18:25:13,602 - INFO - Operation: read_binary performed on file: test.txt - log_manager.py:59
2025-04-15 18:25:13,602 - INFO - Operation: backup_created performed on file: test.txt.bak - log_manager.py:59
2025-04-15 18:25:13,602 - INFO - Operation: backup performed on file: test.txt.bak - log_manager.py:59
2025-04-15 18:25:13,618 - INFO - Operation: write_binary performed on file: test.txt - log_manager.py:59
2025-04-15 18:25:13,618 - INFO - Operation: decrypt performed on file: test.txt - log_manager.py:59
2025-04-15 18:25:49,597 - INFO - Operation: validate_access_success performed on file: test.txt - log_manager.py:59
2025-04-15 18:25:51,130 - INFO - Operation: read_binary performed on file: test.txt - log_manager.py:59
2025-04-15 18:25:51,146 - INFO - New encryption key generated - crypto_engine.py:17
2025-04-15 18:25:51,146 - INFO - Using newly generated encryption key - crypto_engine.py:27
2025-04-15 18:25:51,157 - INFO - Operation: write_binary performed on file: test.txt - log_manager.py:59
2025-04-15 18:25:51,159 - INFO - Operation: encrypt performed on file: test.txt - log_manager.py:59
2025-04-15 18:26:07,073 - INFO - Operation: read_binary performed on file: test.txt - log_manager.py:59
2025-04-15 18:26:07,073 - INFO - Operation: backup_created performed on file: test.txt.bak - log_manager.py:59
2025-04-15 18:26:07,088 - INFO - Operation: backup performed on file: test.txt.bak - log_manager.py:59
2025-04-15 18:26:07,095 - INFO - Operation: write_binary performed on file: test.txt - log_manager.py:59
2025-04-15 18:26:07,095 - INFO - Operation: decrypt performed on file: test.txt - log_manager.py:59
2025-04-15 18:26:40,222 - INFO - Application shutting down... - main.py:97
2025-04-15 18:28:05,130 - INFO - Logger initialized with rotating file handler. - log_manager.py:49
2025-04-15 18:28:05,130 - INFO - Application starting... - main.py:75
2025-04-15 18:28:05,209 - INFO - Application initialized successfully. Version: 1.0.0 - main.py:126
2025-04-15 18:28:18,728 - INFO - Application shutting down... - main.py:97
2025-04-15 18:45:33,559 - INFO - Logger initialized with rotating file handler. - log_manager.py:49
2025-04-15 18:45:33,559 - INFO - Application starting... - main.py:75
2025-04-15 18:45:33,667 - ERROR - Error Type: StartupError | Message: Failed to initialize application: module 'config' has no attribute 'THEME_COLOR' - log_manager.py:68
2025-04-15 18:46:35,437 - INFO - Logger initialized with rotating file handler. - log_manager.py:49
2025-04-15 18:46:35,437 - INFO - Application starting... - main.py:75
2025-04-15 18:46:35,567 - INFO - Application initialized successfully. Version: 1.0.0 - main.py:126
2025-04-15 18:46:43,366 - INFO - Operation: validate_access_success performed on file: test.txt - log_manager.py:59
2025-04-15 18:46:48,150 - INFO - Operation: read_binary performed on file: test.txt - log_manager.py:59
2025-04-15 18:46:48,154 - INFO - New encryption key generated - crypto_engine.py:17
2025-04-15 18:46:48,154 - INFO - Using newly generated encryption key - crypto_engine.py:27
2025-04-15 18:46:48,200 - INFO - Operation: write_binary performed on file: test.txt - log_manager.py:59
2025-04-15 18:46:48,200 - INFO - Operation: encrypt performed on file: test.txt - log_manager.py:59
2025-04-15 18:46:59,333 - INFO - Operation: read_binary performed on file: test.txt - log_manager.py:59
2025-04-15 18:46:59,333 - INFO - Operation: backup_created performed on file: test.txt.bak - log_manager.py:59
2025-04-15 18:46:59,348 - INFO - Operation: backup performed on file: test.txt.bak - log_manager.py:59
2025-04-15 18:46:59,356 - INFO - Operation: write_binary performed on file: test.txt - log_manager.py:59
2025-04-15 18:46:59,356 - INFO - Operation: decrypt performed on file: test.txt - log_manager.py:59
2025-04-15 18:47:48,327 - INFO - Application shutting down... - main.py:97
2025-04-15 18:47:59,032 - INFO - Logger initialized with rotating file handler. - log_manager.py:49
2025-04-15 18:47:59,032 - INFO - Application starting... - main.py:75
2025-04-15 18:47:59,162 - INFO - Application initialized successfully. Version: 1.0.0 - main.py:126
2025-04-15 18:50:16,927 - INFO - Application shutting down... - main.py:97
2025-04-15 18:50:21,220 - INFO - Logger initialized with rotating file handler. - log_manager.py:49
2025-04-15 18:50:21,220 - INFO - Application starting... - main.py:75
2025-04-15 18:50:21,335 - INFO - Application initialized successfully. Version: 1.0.0 - main.py:126
2025-04-15 18:50:28,601 - INFO - Application shutting down... - main.py:97
2025-04-15 18:52:31,013 - INFO - Logger initialized with rotating file handler. - log_manager.py:49
2025-04-15 18:52:31,013 - INFO - Application starting... - main.py:75
2025-04-15 18:52:31,115 - INFO - Application initialized successfully. Version: 1.0.0 - main.py:126
2025-04-15 18:55:16,580 - INFO - Application shutting down... - main.py:97
2025-04-15 18:55:22,230 - INFO - Logger initialized with rotating file handler. - log_manager.py:49
2025-04-15 18:55:22,230 - INFO - Application starting... - main.py:75
2025-04-15 18:55:22,355 - INFO - Application initialized successfully. Version: 1.0.0 - main.py:126
2025-04-15 18:56:22,249 - INFO - Application shutting down... - main.py:97
2025-04-15 18:56:25,283 - INFO - Logger initialized with rotating file handler. - log_manager.py:49
2025-04-15 18:56:25,283 - INFO - Application starting... - main.py:75
2025-04-15 18:56:25,398 - INFO - Application initialized successfully. Version: 1.0.0 - main.py:126
2025-04-15 18:59:21,910 - INFO - Application shutting down... - main.py:97
2025-04-15 19:05:06,572 - INFO - Logger initialized with rotating file handler. - log_manager.py:49
2025-04-15 19:05:06,572 - INFO - Application starting... - main.py:75
2025-04-15 19:05:06,718 - INFO - Application initialized successfully. Version: 1.0.0 - main.py:126
2025-04-15 19:05:15,545 - INFO - Application shutting down... - main.py:97
2025-04-15 20:33:39,874 - INFO - Logger initialized with rotating file handler. - log_manager.py:49
2025-04-15 20:33:39,876 - INFO - Application starting... - main.py:75
2025-04-15 20:33:41,205 - INFO - Application initialized successfully. Version: 1.0.0 - main.py:126
2025-04-15 20:33:46,265 - INFO - Application shutting down... - main.py:97
2025-04-15 20:34:51,708 - INFO - Logger initialized with rotating file handler. - log_manager.py:49
2025-04-15 20:34:51,710 - INFO - Application starting... - main.py:75
2025-04-15 20:34:51,793 - INFO - Application initialized successfully. Version: 1.0.0 - main.py:126
2025-04-15 20:34:56,196 - INFO - Application shutting down... - main.py:97
2025-04-15 20:37:50,476 - INFO - Logger initialized with rotating file handler. - log_manager.py:49
2025-04-15 20:37:50,477 - INFO - Application starting... - main.py:75
2025-04-15 20:37:50,548 - ERROR - Error Type: StartupError | Message: Failed to initialize application: module 'config' has no attribute 'FONT_COLOR' - log_manager.py:68
2025-04-15 20:39:46,279 - INFO - Logger initialized with rotating file handler. - log_manager.py:49
2025-04-15 20:39:46,279 - INFO - Application starting... - main.py:75
2025-04-15 20:39:47,203 - INFO - Application initialized successfully. Version: 1.0.0 - main.py:126
2025-04-15 20:40:10,995 - INFO - Operation: validate_access_success performed on file: test.txt - log_manager.py:59
2025-04-15 20:42:02,577 - INFO - Application shutting down... - main.py:97
2025-04-15 20:47:18,135 - INFO - Logger initialized with rotating file handler. - log_manager.py:49
2025-04-15 20:47:18,135 - INFO - Application starting... - main.py:75
2025-04-15 20:47:18,213 - INFO - Application initialized successfully. Version: 1.0.0 - main.py:126
2025-04-15 20:47:39,603 - INFO - Operation: validate_access_success performed on file: test.txt - log_manager.py:59
2025-04-15 20:47:41,711 - INFO - Operation: read_binary performed on file: test.txt - log_manager.py:59
2025-04-15 20:47:41,711 - INFO - New encryption key generated - crypto_engine.py:17
2025-04-15 20:47:41,711 - INFO - Using newly generated encryption key - crypto_engine.py:27
2025-04-15 20:47:41,763 - INFO - Operation: write_binary performed on file: test.txt - log_manager.py:59
2025-04-15 20:47:41,763 - INFO - Operation: encrypt performed on file: test.txt - log_manager.py:59
2025-04-15 20:48:05,256 - INFO - Operation: read_binary performed on file: test.txt - log_manager.py:59
2025-04-15 20:48:05,260 - INFO - Operation: backup_created performed on file: test.txt.bak - log_manager.py:59
2025-04-15 20:48:05,260 - INFO - Operation: backup performed on file: test.txt.bak - log_manager.py:59
2025-04-15 20:48:05,268 - INFO - Operation: write_binary performed on file: test.txt - log_manager.py:59
2025-04-15 20:48:05,268 - INFO - Operation: decrypt performed on file: test.txt - log_manager.py:59
2025-04-15 21:41:35,404 - INFO - Application shutting down... - main.py:97
2025-04-15 21:41:40,472 - INFO - Logger initialized with rotating file handler. - log_manager.py:49
2025-04-15 21:41:40,472 - INFO - Application starting... - main.py:75
2025-04-15 21:41:40,553 - INFO - Application initialized successfully. Version: 1.0.0 - main.py:126
2025-04-15 21:41:58,525 - INFO - Operation: validate_access_success performed on file: test.txt - log_manager.py:59
2025-04-15 21:42:03,950 - INFO - Operation: read_binary performed on file: test.txt - log_manager.py:59
2025-04-15 21:42:03,950 - INFO - New encryption key generated - crypto_engine.py:17
2025-04-15 21:42:03,950 - INFO - Using newly generated encryption key - crypto_engine.py:27
2025-04-15 21:42:03,972 - INFO - Operation: write_binary performed on file: test.txt - log_manager.py:59
2025-04-15 21:42:03,972 - INFO - Operation: encrypt performed on file: test.txt - log_manager.py:59
2025-04-15 21:42:21,180 - INFO - Operation: read_binary performed on file: test.txt - log_manager.py:59
2025-04-15 21:42:21,180 - INFO - New encryption key generated - crypto_engine.py:17
2025-04-15 21:42:21,180 - INFO - Using newly generated encryption key - crypto_engine.py:27
2025-04-15 21:42:21,180 - INFO - Operation: write_binary performed on file: test.txt - log_manager.py:59
2025-04-15 21:42:21,180 - INFO - Operation: encrypt performed on file: test.txt - log_manager.py:59
2025-04-15 21:42:28,717 - INFO - Operation: read_binary performed on file: test.txt - log_manager.py:59
2025-04-15 21:42:28,720 - INFO - Operation: backup_created performed on file: test.txt.bak - log_manager.py:59
2025-04-15 21:42:28,720 - INFO - Operation: backup performed on file: test.txt.bak - log_manager.py:59
2025-04-15 21:42:28,720 - ERROR - Error Type: DecryptionError | Message: Decryption failed - Invalid token - log_manager.py:68
2025-04-15 21:42:28,720 - ERROR - Error Type: DecryptionError | Message: Unexpected error during decryption: ValueError - log_manager.py:68
2025-04-15 21:42:32,557 - INFO - Operation: read_binary performed on file: test.txt - log_manager.py:59
2025-04-15 21:42:32,557 - INFO - Operation: backup_created performed on file: test.txt.bak - log_manager.py:59
2025-04-15 21:42:32,557 - INFO - Operation: backup performed on file: test.txt.bak - log_manager.py:59
2025-04-15 21:42:32,567 - INFO - Operation: write_binary performed on file: test.txt - log_manager.py:59
2025-04-15 21:42:32,567 - INFO - Operation: decrypt performed on file: test.txt - log_manager.py:59
2025-04-15 21:42:36,947 - INFO - Application shutting down... - main.py:97
2025-04-15 21:43:07,443 - INFO - Logger initialized with rotating file handler. - log_manager.py:49
2025-04-15 21:43:07,443 - INFO - Application starting... - main.py:75
2025-04-15 21:43:07,521 - INFO - Application initialized successfully. Version: 1.0.0 - main.py:126
2025-04-15 21:43:30,420 - INFO - Operation: validate_access_success performed on file: test.txt - log_manager.py:59
2025-04-15 21:43:31,809 - INFO - Operation: read_binary performed on file: test.txt - log_manager.py:59
2025-04-15 21:43:31,810 - INFO - New encryption key generated - crypto_engine.py:17
2025-04-15 21:43:31,810 - INFO - Using newly generated encryption key - crypto_engine.py:27
2025-04-15 21:43:31,823 - INFO - Operation: write_binary performed on file: test.txt - log_manager.py:59
2025-04-15 21:43:31,823 - INFO - Operation: encrypt performed on file: test.txt - log_manager.py:59
2025-04-15 21:43:50,274 - INFO - Operation: read_binary performed on file: test.txt - log_manager.py:59
2025-04-15 21:43:50,275 - INFO - Operation: backup_created performed on file: test.txt.bak - log_manager.py:59
2025-04-15 21:43:50,275 - INFO - Operation: backup performed on file: test.txt.bak - log_manager.py:59
2025-04-15 21:43:50,282 - INFO - Operation: write_binary performed on file: test.txt - log_manager.py:59
2025-04-15 21:43:50,282 - INFO - Operation: decrypt performed on file: test.txt - log_manager.py:59
2025-04-15 21:43:59,254 - INFO - Application shutting down... - main.py:97
2025-04-15 21:49:35,642 - INFO - Logger initialized with rotating file handler. - log_manager.py:49
2025-04-15 21:49:35,642 - INFO - Application starting... - main.py:75
2025-04-15 21:49:35,721 - INFO - Application initialized successfully. Version: 1.0.0 - main.py:126
2025-04-15 21:49:56,906 - INFO - Application shutting down... - main.py:97
